repos:
  # prettier - yaml, json, markdown, sql
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        types_or: [yaml, json, markdown, sql]

  # gofmt - go
  - repo: local
    hooks:
      - id: go-fmt
        name: go fmt
        entry: go fmt ./..
        language: system
        files: \.go$
        pass_filenames: false

      - id: go-imports
        name: go imports
        entry: goimports -w
        language: system
        files: \.go$

  # ruff - python
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.2
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format

  # security check for leaked secrets
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        exclude: .*/migrations/.* # migrations may appear as secrets, so they should be excluded from secret checks
